# Generated by Django 4.2.7 on 2023-12-05 23:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Contacts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='time',
            new_name='created_time',
        ),
    ]
